- hosts: 127.0.0.1
  remote_user: root
  vars:
    go_file: go1.4.linux-amd64.tar.gz
    go_install_dir: /usr/local
    go_path: /vagrant/go
    work_dir: /tmp/

  tasks:
  - name: wget go binary
    get_url: url="https://storage.googleapis.com/golang/{{ go_file }}" dest={{ work_dir }} mode=0644

  - name: unarchive
    shell: sudo tar -C {{ go_install_dir }} -xzf {{ go_file }}
    args:
      chdir: "{{ work_dir }}"

  - name: create Go tools directory
    file: path="{{ go_path }}" state=directory

  - name: add Go ROOT to environment variable
    shell: echo "export GOROOT={{ go_install_dir }}/go" >> $HOME/.profile

  - name: add Go PATH to environment variable
    shell: echo "export GOPATH={{ go_path }}" >> $HOME/.profile

  - name: add go PATH to environment variable
    shell: echo "export PATH=$PATH:{{ go_install_dir }}/go/bin:{{ go_path }}/bin" >> $HOME/.profile

