- hosts: 127.0.0.1
  remote_user: root
  vars:
    go_file: go1.5.2.linux-amd64.tar.gz
    go_install_dir: /usr/local
    go_path: /vagrant/go
    work_dir: /tmp
    zsh_id: 1555225
    tmux_id: 1779907
    zsh_mark: zsh
    tmux_mark: tmuz

  tasks:
  - name: wget go binary
    get_url: url="https://storage.googleapis.com/golang/{{ go_file }}" dest={{ work_dir }} mode=0644

  - name: unarchive
    shell: sudo tar -C {{ go_install_dir }} -xzf {{ go_file }}
    args:
      chdir: "{{ work_dir }}"

  - name: create Go tools directory
    file: path="{{ go_path }}" state=directory

  - name: add Go ROOT to environment variable
    shell: echo "export GOROOT={{ go_install_dir }}/go" >> {{ ansible_env.HOME }}/.profile

  - name: add Go PATH to environment variable
    shell: echo "export GOPATH={{ go_path }}" >> {{ ansible_env.HOME }}/.profile

  - name: add goroot and gopath to environment variable
    shell: echo "export PATH=$PATH:{{ go_install_dir }}/go/bin:{{ go_path }}/bin" >> {{ ansible_env.HOME }}/.profile

  - name: upgrade packages
    apt: update_cache=ues upgrade=dist
    sudo: yes

  - name: install git
    apt: name=git state=latest
    sudo: yes

  - name: install mercurial
    apt: name=mercurial state=latest
    sudo: yes

  - name: go get gocode
    shell: . $HOME/.profile && go get -u github.com/nsf/gocode

  - name: go get godef
    shell: . $HOME/.profile && go get code.google.com/p/rog-go/exp/cmd/godef

  - name: install emacs
    apt: name=emacs state=latest
    sudo: yes

  - name: install spacemacs
    git: repo=https://github.com/syl20bnr/spacemacs.git dest={{ ansible_env.HOME }}/.emacs.d

  - name: chown .emacs.d
    file: path={{ ansible_env.HOME }}/.emacs.d owner=vagrant group=vagrant recurse=yes state=directory

  - name: install zsh
    apt: name=zsh state=latest

  - name: get .zshrc
    git: repo=https://gist.github.com/atakig/"{{ zsh_id }}" dest="{{ work_dir }}"/"{{ zsh_mark }}"

  - name: copy .zshrc
    shell: create="{{ work_dir }}"/"{{ zsh_mark }}"/dot.zshrc cp "{{ work_dir }}"/"{{ zsh_mark }}"/dot.zshrc {{ ansible_env.HOME }}/.zshrc

  - name: get .tmux.conf
    git: repo=https://gist.github.com/atakig/"{{ tmux_id }}"/dot_tmux dest="{{ work_dir }}"/"{{ tmux_mark }}"

  - name: copy .tmux.conf
    shell: create="{{ work_dir }}"/"{{ tmux_id }}"/dot.tmux.conf cp "{{ work_dir }}"/"{{ tmux_mark }}"/dot.tmux.conf {{ ansible_env.HOME }}/.tmux.conf
