- hosts: 127.0.0.1
  remote_user: root
  vars:
    pg_hba_conf: /etc/postgresql/9.3/main/pg_hba.conf
    db_name: accounts
    user_name: ac_user
    password: ac_pass

  tasks:
  - name: install postgresql
    apt: name=postgresql state=present
    sudo: yes

  - name: install postgresql
    apt: name=python-psycopg2 state=present
    sudo: yes

  - name: add user auth
    lineinfile:  dest="{{ pg_hba_conf }}" state=present line="local {{ db_name }} {{ user_name }} password"
    sudo: yes

  - name: start postgresql
    service: name=postgresql state=restarted
    sudo: yes

  - name: setup database
    postgresql_db: name="{{ db_name }}" encoding='UTF-8'

  - name: setup user
    postgresql_user: db="{{ db_name }}" name="{{ user_name }}" password="{{ password }}"

  - name: setup privs
    postgresql_privs: database="{{ db_name }}" roles="{{ user_name }}" type=database priv=ALL
